### ISSUE TITLE
Start up error

### ISSUE THREAD

**Issue by airstring** [jertel/elastalert2#1054]
There was an error when starting：
elasticalert-elastalert-1  | elastalert.util.EAException: Error loading file /opt/elastalert/rules/smtp_auth_file.yml: Invalid Rule file: /opt/elastalert/rules/smtp_auth_file.yml
elasticalert-elastalert-1  | 'type' is a required property

cat rules/smtp_auth_file.yml
user: "zsdf@gmail.com"
password: "123456"

**Comment by jertel** [comment]
Please do not double post. See #11 for project guidelines.
