### ISSUE TITLE
Readme out of date

### ISSUE THREAD

**Issue by archfz** [jertel/elastalert2#109]
In newest image /opt/config/elastalert_config.yaml needs to be mounted. The readme says otherwise.

**Comment by jertel** [comment]
Are you using the newest Docker image tagged `jertel/elastalert2:latest`?

**Comment by archfz** [comment]
Using 2.0.4

**Comment by jertel** [comment]
Yes, that makes sense. We're in a bit of an awkward state right now since the Readme reflects the latest version, not the most recent release. If you used the `latest` tag it would align properly with the Readme.
