### ISSUE TITLE
Add initContainers option in helm chart

### ISSUE THREAD

**Issue by aturpin1789** [jertel/elastalert2#1140]
### Discussed in https://github.com/jertel/elastalert2/discussions/1134

<div type='discussions-op-text'>

<sup>Originally posted by **aturpin1789** March 15, 2023</sup>
Hello

I would like to propose adding the possibilities to add initContainers configuration to helm chart.
My goal is to create a container that will pull my rules directory from my gitlab repo and then apply the transformation configured in helm release config file.
I could add another container to do the job but, firstly I can not be sure that rules will be loaded before the transformation are applied and secondly, I do not want a one-shot container created.

Is this an interesting ideas ?</div>

**Comment by aturpin1789** [comment]
Hello @jertel

Could you apply those changes in Artifact Hub ?

Thanks

**Comment by jertel** [comment]
They will be applied with the next release, which should occur within the next few days.

**Comment by aturpin1789** [comment]
Thank you, I will look forward to it.
