### ISSUE TITLE
The rules matched, but for some reason they were silenced

### ISSUE THREAD

**Issue by wangchao732** [jertel/elastalert2#1487]
If you don't want it silenced, why do you specify realert of 1 hour?
![image](https://github.com/jertel/elastalert2/assets/16639611/e68bb1c3-fd10-4584-94a7-bb82fe1ae3dc)

Also, please read #11 and format your messages appropriately. It's difficult to read them without proper formatting.

_Originally posted by @jertel in https://github.com/jertel/elastalert2/issues/1484#issuecomment-2205732407_

**Comment by wangchao732** [comment]
@jertel   And not as you understand, yesterday by execution  bin/elastalert-test-rule  rules/prod.yaml --config config.yaml --alert
Successfully received the alert message. But bin/python3 -m elastalert.elastalert  --config config.yaml --verbose  isn't received the alert message.
![image](https://github.com/jertel/elastalert2/assets/19440083/f60be360-72a1-4b96-a4be-1caf70e1fdb4)

Today test again, try to delete elastalert_status_silence doc. Start and Successfully received the alert message. 
delete all index elastalert_*  ,Recreate elastalert_* index with bin/elastalert-create-index,  Start and Successfully received the alert message. 

So, I don't know exactly what the problem is, but it looks healthy after rebuilding by removing the index at the moment.

**Comment by jertel** [comment]
Please read #11 and avoid creating issues when requesting support.
