### ISSUE TITLE
I run a elasticsearch search query where i want to trigger Alert on basis of Message Out of Memory but it is filtering those documents also which has Out only

### ISSUE THREAD

**Issue by ishukeshri2712** [jertel/elastalert2#1491]
I run a elasticsearch search query where i want to trigger Alert on basis of Message Out of Memory but it is filtering those documents also which has Out only plse help how to run elastalert query for this

**Comment by jertel** [comment]
Please read #11 and follow those instructions. Do not open issues when seeking support.
