### ISSUE TITLE
Alarm rules cannot be filtered out of '## xx' using the Querry syntax

### ISSUE THREAD

**Issue by wangchao732** [jertel/elastalert2#1492]
- bool:
    must: [{"match": {"fields.namespace": "dapr-application" }},{"match": { "message": "ERROR" }}]
    must_not: [ {"match": {"message": "WARN"}},{"match": {"message": "DEBUG"}},{"match": {"message": "INFO"}},{"match": {"message": "object is invalid"}},{"match": {"message": "adThread"}},{"match": {"message": "### The error"}} ]

**Comment by wangchao732** [comment]
sorry this issue with elasitc.

![~XD~VGD OZQC_UN~HOI6J9D](https://github.com/user-attachments/assets/90807f41-d9bd-4b1c-acee-2a0ae5e97a83)
![XCR`PVFTD7K2$1TD()G7Z0A](https://github.com/user-attachments/assets/911e7c50-b495-4f10-8961-66084d5f2454)

**Comment by jertel** [comment]
Please read #11 and open a new Discussions for support.
