### ISSUE TITLE
All alarms in the rule are silenced

### ISSUE THREAD

**Issue by wangchao732** [jertel/elastalert2#1498]
I only have one rule, I want to make each alarm only generate once, and the repeated alarm is silent for an hour, but each time it seems to silence the whole rule? Why is that?

{
  "_index" : "elastalert_status_silence",
  "_id" : "gDpZd5ABVEXVlDRlmDgv",
  "_version" : 1,
  "_seq_no" : 0,
  "_primary_term" : 1,
  "found" : true,
  "_source" : {
    "exponent" : 0,
    "rule_name" : "Prod Rule._silence",
    "@timestamp" : "2024-07-03T06:47:58.744077Z",
    "until" : "2024-07-03T06:47:58.744067Z"
  }
}

There will be multiple different alarms in a rule, but it seems that the whole rule is silent.

name: Prod Rule
type: any
index: k8slog*
num_events: 1
timeframe:
  minutes: 5
realert:
  hours: 1

**Comment by jertel** [comment]
Read #11 . Issues are for verified software bugs, not for asking for support. Open a discussion.
