### ISSUE TITLE
[Helm] Secrets in Elastalert Helm Chart

### ISSUE THREAD

**Issue by operatorequals** [jertel/elastalert2#152]
Hello people!
Thank you for maintaining this project!

I wanted to point out the issue on the Helm Chart, that all Elasticsearch credentials are stored in a ConfigMap (and not in a Secret).

I have fixed this issue myself some half a year ago here: https://github.com/operatorequals/elastalert-helm/tree/master/templates
for my needs on a Cloud SIEM I am making ([Blue-Baron](https://github.com/operatorequals/Blue-Baron)).

I have not much time in my hands to make a proper PR, but as you are into maintaining Elastalert, it would be great to take ideas out of this Helm chart, that was made with security in mind.

I am really rooting for you in this one! I am using Elastalert and [Praeco](https://github.com/johnsusek/praeco) a lot in my SIEM builds ([here is one example](https://build.thebeat.co/security-sky-gazing-16cf158a759a)).

**Comment by jertel** [comment]
This is not correct. The existing chart supports storing the ES username and password in a configmap OR in a secret. This is documented on the Chart README and can be verified by reviewing the deployment.yaml.

**Comment by operatorequals** [comment]
Hello @jertel !

Indeed, there is a Secret option, but you have to provide the Secret resource yourself!
I am talking more or less about changing this line 
https://github.com/jertel/elastalert2/blob/master/chart/elastalert2/templates/config.yaml#L3
to `kind: Secret` and create the Secret resource directly from the Helm chart.

Right now, if I set the credentials literal values in the Helm chart (e.g set `elasticsearch.password`) this is gonna end up in the `ConfigMap` (https://github.com/jertel/elastalert2/blob/master/chart/elastalert2/templates/config.yaml#L27).

Please correct me if I am being mistaken.

**Comment by jertel** [comment]
When it comes to storing the entire configuration file as a secret that gets into personal preference. I personally prefer to limit secrets to only include sensitive values, and I prefer to manage secret resources, outside of the chart.

As it stands today, the chart supports protecting the ES credentials as a secret. But if someone wants to add an _optional_ method for storing the entire configuration as a secret, that's fine. But it should remain optional.

**Comment by operatorequals** [comment]
I see your point.
I am closing this!
