### ISSUE TITLE
limit_execution acts like a buffer

### ISSUE THREAD

**Issue by fberrez** [jertel/elastalert2#160]
When an alert is triggered during the inactivity period of a rule having the `limit_execution` option set, elastalert sends an alert at wake up time.

However, the purpose of the `limit_execution` option is to **disable** the alert, not doing the same thing as `aggregation`. 

example:
----

```yaml
limit_execution: * 7-22 * * *
```

A valid event occurs at 01:05am. Therefore, at 7:00am, an alert is sent by elastalert saying:

```txt
an alert occured at 01:05am....
```

**Comment by nsano-rururu** [comment]
There is a comment that implements a function that only limits the execution of rules to a specific time of the day, rather than disabling alerts.

https://github.com/Yelp/elastalert/issues/492#issuecomment-438024625
>I've merged this feature into a new branch, beta, and released it as a new package version 0.2.0b1 available on pypi.
>
>This includes a couple other changes as well, like threading support, but you can now limit rule execution to certain times of the day using limit_execution using cron syntax. For example
>
>limit_execution: "* 7-22 * * *"
>Would mean to only run the rule between 7 am and 10 pm every day.
>
>This feature is still in beta, of course, but you're welcome to try.

**Comment by nsano-rururu** [comment]
The following features seem to be what you mean by `limit_execution`.

Elastalert_hour_range
https://github.com/0xSeb/elastalert_hour_range
[Elastalert] Enable alert only in specific hour range
https://marchal.tech/blog/2019/08/27/elastalert-enable-alert-only-in-specific-hour-range/

**Comment by nsano-rururu** [comment]
Summary

- Qmando created a function that executes rules only at specific times.
- The URL mentioned earlier in the comment is a function that generates only alerts within or outside the specific time zone.

**Comment by fberrez** [comment]
Alright thank you
