### ISSUE TITLE
Add alert_text support for HTTP POST

### ISSUE THREAD

**Issue by immaro** [jertel/elastalert2#165]
Original issue:
https://github.com/Yelp/elastalert/issues/2083

Currently, there is no option to send alert_text with http post:
Neither via http_post_payload, nor via http_post_static_payload.

As a result, it is unable to generate arbitrary message string (with variables).
Please add alert_text support for HTTP POST.

**Comment by just1900** [comment]
This can be done by simply adding four lines code in HTTPPostAlerter's alert method.
```
            if 'alert_subject' in self.rule:
                payload['subject'] = self.create_custom_title(matches)
            if 'alert_text' in self.rule:
                payload['content'] = self.create_alert_body(matches)
```
@jertel how do you think of this? If it's needed, I could open a PR.

**Comment by jertel** [comment]
That would be a big help, thanks for offering. It would be good to also update the httppost_test.py with a unit test that shows the new payload structure when this is used.

**Comment by nsano-rururu** [comment]
It seems that it can be supported by incorporating the contents supported by the following elastalert fork into elastalert2.

HTTPPost Alerter should also support alert text and subject
https://github.com/BigDataBoutique/elastalert/commit/42f855f551d14f019654af0db9b1f35fa157dc43
Strip whitespace from HTTP Post alerts
https://github.com/BigDataBoutique/elastalert/commit/b1078ea9f32d47b5467e66c090c0250bb91ab064

**Comment by jertel** [comment]
Closing this since #530 appears to resolve this request.
