### ISSUE TITLE
--patience argument: writeback_alias / self.alias not used

### ISSUE THREAD

**Issue by mrfroggg** [jertel/elastalert2#166]
ElastAlert 2.1.0

This morning, I was testing the `--patience` argument from the elastalert command (`self.args.timeout`):
```
/opt/elastalert $ elastalert --config config.yaml --verbose --rule toto.yaml --patience seconds=60
1 rules loaded
ERROR:elastalert:Writeback alias "elastalert_alerts" does not exist, did you run `elastalert-create-index`?
```

I found out that the class parameter `self.writeback_alias = self.conf['writeback_alias']` is not documented and is not in use anywhere except in the `elastalert.ElastAlerter.wait_until_responsive`:
```
        while (clock() - ref) < timeout:
            try:
                if self.writeback_es.indices.exists(self.writeback_alias):
                    return
            except ConnectionError:
                pass
            time.sleep(1.0)

        if self.writeback_es.ping():
            elastalert_logger.error(
                'Writeback alias "%s" does not exist, did you run `elastalert-create-index`?',
                self.writeback_alias,
            )
```

There is a default:
`conf.setdefault('writeback_alias', 'elastalert_alerts')`

Which is not created by `create_index_mappings`, the alias variable is not in used:
```
        index = args.index if args.index is not None else data.get('writeback_index')
        alias = args.alias if args.alias is not None else data.get('writeback_alias')
```

So, I wonder, should this alias be used, somewhere?
Or should we clean this and use `writeback_index`, instead?

**Comment by jertel** [comment]
It looks to me like it should be replaced with writeback_index and then remove the alias references. I don't see any value in having writeback_alias in the codebase. Here is the original author's commit history. I can't figure out what the purpose was.

https://github.com/Yelp/elastalert/commits?author=pdscopes

**Comment by mrfroggg** [comment]
I found: https://github.com/Yelp/elastalert/pull/2025 + https://github.com/Yelp/elastalert/pull/1598

If I understand, it seems that this was a way to make EA do kind of rollovers/ILM on the client side (EA) instead of on ES side.
Since this has nothing to do with Elasticsearch aliases and the code isn't complete, I also think we should remove this writeback_alias and use writeback_index instead, I can work on it!

**Comment by jertel** [comment]
Ok, so it was mostly contained to the beta branch but this small piece leaked into master at some point. That explains it. Thanks.
