### ISSUE TITLE
Elastalert error out when used with a bearer token

### ISSUE THREAD

**Issue by akilada** [jertel/elastalert2#168]
I'm trying to deploy elasrtalert2 version 2.1.0 on OCP 4.6 to integrate with OpenShift's out of the box EFK stack. I used the 'jertel/elastalert2:latest' image.

I created a dedicated service account for Elastalert. Then added it to `./sgconfig/roles_mapping.yml`. However, the elastalert gave the following error.

`elastalert-create-index --config <config> --index <index_name>`

```
Traceback (most recent call last):
  File "/usr/local/bin/elastalert-create-index", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/elastalert/create_index.py", line 253, in main
    es = Elasticsearch(
  File "/usr/local/lib/python3.9/site-packages/elasticsearch/client/__init__.py", line 206, in __init__
    self.transport = transport_class(_normalize_hosts(hosts), **kwargs)
  File "/usr/local/lib/python3.9/site-packages/elasticsearch/transport.py", line 108, in __init__
    self.set_connections(hosts)
  File "/usr/local/lib/python3.9/site-packages/elasticsearch/transport.py", line 157, in set_connections
    connections = list(zip(connections, hosts))
  File "/usr/local/lib/python3.9/site-packages/elasticsearch/transport.py", line 154, in _create_connection
    return self.connection_class(**kwargs)
  File "/usr/local/lib/python3.9/site-packages/elasticsearch/connection/http_requests.py", line 39, in __init__
    self.session.headers.setdefault('content-type', 'application/json')
AttributeError: 'str' object has no attribute 'setdefault'
```

The elastalert config looks like below:

```
# This is the folder that contains the rule yaml files
# Any .yaml file will be loaded as a rule
rules_folder: /opt/elastalert/rules

#
scan_subdirectories: false

# How often ElastAlert will query elasticsearch
# The unit can be anything from weeks to seconds
run_every:
  minutes: 1

# ElastAlert will buffer results from the most recent
# period of time, in case some log sources are not in real time
buffer_time:
  minutes: 15

# The elasticsearch service for metadata writeback
# Note that every rule can have it's own elasticsearch host
es_host: elasticsearch.openshift-logging.svc.cluster.local

# The elasticsearch port
es_port: 9200

es_bearer: <token>


# The index on es_host which is used for metadata storage
# This can be a unmapped index, but it is recommended that you run
# elastalert-create-index to set a mapping
writeback_index: elastalert_status

# If an alert fails for some reason, ElastAlert will retry
# sending the alert until this time period has elapsed
alert_time_limit:
  days: 2

use_ssl: True
verify_certs: True

# The secrets from the fluent must be mounted!
ca_certs: <ca_cert>
#client_cert:
#client_key: 
```

**Comment by ferozsalam** [comment]
Hey @akilada - thanks for reporting this, this issue seems to have been introduced in a recent change (see [here](https://github.com/jertel/elastalert2/pull/85)).

Are you able to test some patched code for me? I don't have access to an ES cluster with Bearer token auth enabled, and would like to confirm my proposed change works before merging.

**Comment by akilada** [comment]
Hey Feroz

Yeah I can test a patch.

Best Regards,
Akila Amarathunga

**Comment by ferozsalam** [comment]
If you could test my changes at https://github.com/jertel/elastalert2/pull/169, that would be much appreciated.

**Comment by akilada** [comment]
@StribPav - have you seen this issues?

**Comment by jertel** [comment]
If @StribPav did the PR testing on an existing ES cluster, with Elastalert indices already created, then it would explain how this issue could have been missed.

**Comment by StribPav** [comment]
I had a test environment with empty elasticsearch:7.10.1 (discovery. type: single-node)  for ElastAlert indices and ElasticSearch:5.6 with data indices. In my solution, it was a bad idea to save ElastAlert indices in the same Elasticsearch(permissions, the naming convention for indices name, etc). ​I will be able to check this solution only this weekend.

**Comment by StribPav** [comment]
> @StribPav - have you seen this issues?



> @StribPav - have you seen this issues?

I will be able to check this solution only this weekend.

**Comment by akilada** [comment]
@ferozsalam - Your patch works.

I added the patch into release 2.1.0 code and built a new image. 
```
Elastic Version: 6.8.1
Reading Elastic 6 index mappings:
Reading index mapping 'es_mappings/6/silence.json'
Reading index mapping 'es_mappings/6/elastalert_status.json'
Reading index mapping 'es_mappings/6/elastalert.json'
Reading index mapping 'es_mappings/6/past_elastalert.json'
Reading index mapping 'es_mappings/6/elastalert_error.json'
Index elastalert_status already exists. Skipping index creation.
46 rules loaded
```

**Comment by ferozsalam** [comment]
Thanks for checking 👍

**Comment by jertel** [comment]
Closing. Thanks for the patch @ferozsalam.
