### ISSUE TITLE
Send interger tag to thehive alerter

### ISSUE THREAD

**Issue by ryukam** [jertel/elastalert2#201]
Hi all, 

We tried to send an alert to thehive by puting in TAGS a number (integer), This didn't work.
Afrer some analysis, we saw that thehive api is waiting for only strings in TAGS. We modified elatalert code and WE FORCED to convert Tags sent to thehive to string by :

```
class HiveAlerter(Alerter): 
  ...
  ...
  def load_tags(self, tag_names: list, match: dict):
    tag_values = set()
    for tag in tag_names:
        tag_value = self.lookup_field(match, tag, tag)
        if isinstance(tag_value, list):
            for sub_tag in tag_value:
                tag_values.add(str(sub_tag))
        else:
            tag_values.add(str(tag_value))

    return tag_values
```
For **sub_tag** and **tag_value** thehive4py is waiting string values, so we forced it by using str function. 

https://github.com/TheHive-Project/TheHive4py/blob/1.x/thehive4py/models.py
[class Alert(JSONSerializable)]

This works.

Could you take into account this fix for the futur elastalert release please ?

Thank you very much

Charaf B
SSS

**Comment by ferozsalam** [comment]
Hey @ryukam, thanks for the message. This seems like a reasonable change. Just to understand your use-case better, do you have any more information that you can provide on the value of your integer tags?

In particular, are these integer tags coming from within the YAML itself, or are these value being returned by Elasticsearch as part of a tag lookup?
