### ISSUE TITLE
query_key value is a string instead of a dict

### ISSUE THREAD

**Issue by AntoineBlaud** [jertel/elastalert2#340]
### Behavior
Method  _check_matches_ in ruletypes.py appends the query key as a string. 
So match is a dict composed of simple type like string or integer.

**Rules types impacted:**  
- metric
- percentage

On another side, **all other rules** create match from documents content. The method involved is _add_data(self, data)_

### Example
Suppose that we store documents like this one in the index: 
{'@timestamp': **value**, metadata': { 'ip': **value**} }

- If we use a frequency rule on this index , the match generated will have this template : 

  `[{**'metadata': {'ip**': "10.0.0.1"}, '@timestamp': datetime.datetime(20...o=tzutc()), '@version': '1',  '_id': 'tR46i3oBTsznpu6_lwkh', '_index': 'index', '_type': '_doc'}]`

- If we use a metric rule, the match generated will have this template : 

  `[{**'metadata.ip**': '10.0.0.1' , '@timestamp': datetime.datetime(20...o=tzutc())'}]`

### Possible Solution

Fix _check_matches_ by converting query_key value=`"string1.string2.stringN"` to `["string1']["string2]['stringN"]`

**Comment by nsano-rururu** [comment]
query_key is string or array

string

```
query_key: "host.hostname"
```

or 

array

```
query_key: 
  - "host.hostname"
  - "cloud.instance.id"
  - "system.filesystem.mount_point"
 ```

**Comment by nsano-rururu** [comment]
@AntoineBlaud

What rules do you have problems with?

**Comment by nsano-rururu** [comment]
@AntoineBlaud

What is the reason for not issuing a pull request?

**Comment by nsano-rururu** [comment]
ping

**Comment by AntoineBlaud** [comment]
I can submit a pull request if you're agree with the problem.

**Comment by AntoineBlaud** [comment]
This bug is especially annoying when we use match_enhancement because depending of the rule type, match data does not have the same data structure.

**Comment by jertel** [comment]
This could break existing behavior for those who have written rules that rely upon the string format `"foo.bar": 12` instead of `"foo":{"bar": 12}`. With that in mind it might be best to add the structured object to the match dict, as you are suggesting, but also keep the existing string match for now, and potentially mark it as deprecated in the docs.

**Comment by AntoineBlaud** [comment]
I understand the problematic but we can't put both version of a fied (string and dict) into the same doc. Elasticsearch accepts only one because it converts automatically `{ "string1.string2.string3" : "..."}`  to `{"string1": { "string2": { "string3" }}}`

**Comment by jertel** [comment]
If that's the case then the we will have to identify this as a breaking change in the next release. Long term, I think making all rule types store match data consistently is the right direction.
