### ISSUE TITLE
elastalert-test-rule运行规则生效，而使用python3 -m elastalert.elastalert --config config.yaml --verbose --rule rules/test_frequency.yaml命令不生效

### ISSUE THREAD

**Issue by Zinl** [jertel/elastalert2#366]
使用elastalert-test-rule可以用
![image](https://user-images.githubusercontent.com/30452652/127123619-7aace31b-1217-4dd6-8341-61e4f3d2b8cd.png)
![image](https://user-images.githubusercontent.com/30452652/127123667-0fe94e8e-8db3-4c48-8bac-21af95c155ab.png)
如上图使用elastalert命令不运行规则
config文件如下
![image](https://user-images.githubusercontent.com/30452652/127123855-318f6a07-a6f8-477e-9015-5e44f840f50a.png)
rule文件如下
![image](https://user-images.githubusercontent.com/30452652/127123991-91db321e-66eb-4cfe-856c-f6c75bf404cf.png)
![image](https://user-images.githubusercontent.com/30452652/127124027-7863df6c-f146-494e-a202-6114cad972cb.png)

**Comment by Zinl** [comment]
请问这是什么原因

**Comment by nsano-rururu** [comment]
I'm posting the same content in the discussion, so the issue is closed.
