### ISSUE TITLE
TheHive Configuration

### ISSUE THREAD

**Issue by francisbebe** [jertel/elastalert2#517]
I'm getting issue to get data field value when using elastalert docker version jertel/elastalert2:2.2.2 
I try other version but still getting string like '{rule[name]}' instead of rule name value.
'{rule[name]}'
{match[somefield]}
or {match[_index]}?id={match[_id]}

anyone know how to solve this?? 

---------------------------------------
### Discussed in https://github.com/jertel/elastalert2/discussions/465

<div type='discussions-op-text'>

<sup>Originally posted by **Harris-Chan** September 15, 2021</sup>
HI 

I am creating thehive alert in elastalert. And I want to change the type config in hive_alert_config from 'external' to some match field like index or rule name. However, I found that it can only return the string "index" in the type. How can I do it on `type `while Yelp/elastalert can use match[index].

I tried {_index} or _index on that `type `field but its only return me the string

```
hive_alert_config:
  customFields:
    - name: example
      type: string
      value: example
  follow: True
  severity: 2
  status: 'New'
  source: 'elastalert'
  description: 'Sample description'
  tags: ['tag1', 'tag2']
  title: 'Title'
  tlp: 3
  type: 'external'   <------------ Change it to match field

hive_observable_data_mapping:
  - domain: agent.hostname
  - domain: response.domain
  - ip: client.ip
```</div>

**Comment by jertel** [comment]
Closing due to double-posting into discussions.
