### ISSUE TITLE
WARNING:py.warnings:/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host "<elastic-host>"

### ISSUE THREAD

**Issue by alexku7** [jertel/elastalert2#573]
The elastalert supports the "ssl_show_warn" flag to suppress warnings when it sends alerts to various targets but , as far as I can understand the elastalert doesn't support this flag when it polls the elasticsearch .

In many cases the elastalert2 is deployed ont he same cluster with ELK and polls the elastic via kubernetes internal names, therefore can't verify the TLS certificates. As result the log is blown with InsecureRequestWarning warnings.

**Comment by nsano-rururu** [comment]
It is an option when connecting elasticsearch, not a polling option.
