### ISSUE TITLE
docker run start error

### ISSUE THREAD

**Issue by qq54903099** [jertel/elastalert2#643]
start parameter：docker run -d -v /opt/elastalert2/config.yaml:/opt/elastalert/config.yaml jertel/elastalert2
error log like this:
![image](https://user-images.githubusercontent.com/3895272/148156399-b532c131-d006-4a03-88eb-5d31cb344489.png)

**Comment by nsano-rururu** [comment]
look 
docker example
https://elastalert2.readthedocs.io/en/latest/running_elastalert.html#as-a-docker-container

**Comment by nsano-rururu** [comment]
Did the problem go away? Please stop without any reaction.
