### ISSUE TITLE
Helm Chart: missing "elastalert2/templates/config.yaml"

### ISSUE THREAD

**Issue by farcorben** [jertel/elastalert2#91]
greate job so far  ^^ i found a issue while testing Helm

The latest Helm chart crash with error

`helm upgrade --install elastalert2 jertel/elastalert2

Release "elastalert2" does not exist. Installing it now.
Error: template: elastalert2/templates/deployment.yaml:20:28: executing "elastalert2/templates/deployment.yaml" at <include (print $.Template.BasePath "/config.yaml") .>: error calling include: template: no template "elastalert2/templates/config.yaml" associated with template "gotpl"`

The Template File for "elastalert2/templates/config.yaml"  is missing in Helm Chart also in GIT.

**Comment by jertel** [comment]
Thanks for raising this. It appears the .gitignore file prevented it from being added to Git.

**Comment by jertel** [comment]
Fixed in https://github.com/jertel/elastalert2/commit/75da39f60443c30333e0f06747c7d914b2b6571d.

The corrected chart will not be available until the next release, which I'll try to get out today or tomorrow.

**Comment by farcorben** [comment]
many thanks ^^

**Comment by sunoce** [comment]
Do you plan to release the new version today?  Thank you very much

**Comment by jertel** [comment]
2.0.4 is released. Thanks for your patience!
